### ISSUE TITLE
Invalid token session. Please login again.

### ISSUE THREAD

**Issue by ghost** [opencart-ce/opencart-ce#67]
Hi,

Basically it's a small issue, but it is there. After you login to admin panel, you can't go back (hit browser's "go back" button) to "forgotten password" or "login" screen without seeing "Invalid token session. Please login again.". It is quite obvious - you're logged in, so Opencart redirects you to your admin home screen, but then it can't find token within your url, so you see login screen with error, not home page. You can't even click on "forgotten password" link on login screen because it will redirect you to homepage which doesn't work.

Steps to recreate:
1. Go to admin login screen, login as normal.
2. Go through couple of pages in admin panel.
3. Click on your browser's "go back" button and select directly login screen.
4. Opencart will see that you're logged in, so will redirect to home page.
5. Homepage won't find token within your url, so it will show you login screen.
6. Url actually says admin/index.php?route=common/home (home page)
7. You see error and login screen instead of home page.

My fix currently is to logout user when token is not found, so in admin/controller/common/header after line 135 I put:

```
        $this->user->logout();
        unset($this->session->data['token']);
```

I'm not sure if it will affect anything else, but that's my quick idea.

Thanks!

**Comment by JohnKurt** [comment]
Caros, peço desculpas se aqui não for o melhor lugar pra fazer a pergunta. Estou pronto para migrar minha loja virtual para Opencart. Só me falta uma coisa: preciso de um correção aqui<não consigo acessar minha área administrativa "admin/index.php?route=common/dashboard&token=JaYpM5KN9BbJy9Ue7oj7I93xh3QR0EhA"

**Comment by ADDCreative** [comment]
Wrong place for this try the OpenCart forums. http://forum.opencart.com/

**Comment by kolectorama** [comment]
some light needed here to as you can spend nights to read help forum and if you are lucky ... you will maybe see something interesting in the answer ...
Since I have installed (not sure but it seems) a new module allowing me to load several photos for an item (up 10) I published 4 items then got back to regular item posting. I posted 2 items then started to have a message - while going to the add the default photo (data) - I got the message Invalide Token blah blah login again and lost the item post ...

Got to Opencart forum and saw - after a lot of reads - someone saying to find a code and put a # before WHERE in the username .... I did then got back to post when I find out that Category autocomplete was dead as well as the Downloads ... so ... stuck again
OC V 2.1.0.1  ... www.kolectorama.com ... really need help on this one
Thank you

**Comment by ADDCreative** [comment]
This is a bug tracker for OpenCart Community Edition which doesn't even cover OpenCart version 2. If you are getting no help on the forums, try contacting the developer of the new module you have added. Or one of the companies offering support. http://www.opencart.com/index.php?route=support/support Or OpenCart directly. http://www.opencart.com/index.php?route=support/contact
